### ISSUE TITLE
Volume and Mass Information of Ore in Container

### ISSUE THREAD

**Issue by GezginEmre** [d6rks1lv3rz3r0/DU-Mining-Screen#1]
The variables of the container volume and mass indicators in the lower right part of the screen are written interchangeably.

649: addText(layer, font, string.format("%.1f",Vol) .. "t", X + SX/2 + 25*vh, Y)
653: addText(layer, font, string.format("%.1f",Mass) .. "kL", X + SX/2 + 39*vh, Y)

**Comment by d6rks1lv3rz3r0** [comment]
Fixed.
